export const Roles = [
    { id: 1, value: 'Backend' },
    { id: 2, value: 'Frontend' },
    { id: 3, value: 'Fullstack' },
    { id: 4, value: 'IOS' },
    { id: 5, value: 'Flutter' },
    { id: 6, value: 'React Native' },
    { id: 7, value: 'Android' },
    { id: 8, value: 'Tech Lead' },
    { id: 9, value: 'Dev-Ops' },
    { id: 9, value: 'Data Engineer' },
    { id: 10, value: 'Data Science' },
    { id: 11, value: 'Computer Vision' },
    { id: 12, value: 'NLP' },
    { id: 13, value: 'Deep Learning' },
    { id: 14, value: 'SRE' },
    { id: 15, value: 'Data Infrastructure' },
    { id: 16, value: 'Designer' },
    { id: 17, value: 'Design Manager' },
    { id: 18, value: 'Graphics Designer' },
    { id: 19, value: 'Product Designer' },
    { id: 20, value: 'Product Manager' },
    { id: 21, value: 'Operation Manager' },
    { id: 22, value: "Founder's Office/Cheif's Staff" },
    { id: 23, value: 'Sales Development Representative' },
    { id: 24, value: 'Account Executive' },
    { id: 25, value: 'Account Manager' },
    { id: 26, value: 'Digital Marketing Manager' },
    { id: 27, value: 'Growth Hacker' },
    { id: 28, value: 'Product Marketing Manager' },
    { id: 29, value: 'Hardware' },
    { id: 30, value: 'Mechanical' },
    { id: 31, value: 'Systems' },
    { id: 32, value: 'Business Analyst' },
    { id: 33, value: 'Management' },
    { id: 34, value: 'Legal' },
    { id: 35, value: 'HR' },
    { id: 36, value: 'Finance' },
]

export const numberOfEmployees = [
    { id: 1, value: '1-10' },
    { id: 2, value: '11-20' },
    { id: 3, value: '21-50' },
    { id: 4, value: '51-100' },
    { id: 5, value: '101-200' },
    { id: 6, value: '201-500' },
    { id: 7, value: '500+' },
]

export const experience = [
    { id: 1, value: '1' },
    { id: 2, value: '2' },
    { id: 3, value: '3' },
    { id: 4, value: '4' },
    { id: 5, value: '5' },
    { id: 6, value: '6' },
    { id: 7, value: '7' },
    { id: 8, value: '8' },
    { id: 9, value: '9' },
    { id: 10, value: '10' },
];

export const locations = [
    { id: 1, value: 'Bangalore' },
    { id: 2, value: 'Mumbai' },
    { id: 3, value: 'Delhi' },
    { id: 4, value: 'Hyderabad' },
    { id: 5, value: 'Chennai' },
    { id: 6, value: 'Kolkata' },
    { id: 7, value: 'Pune' },
    { id: 8, value: 'Ahmedabad' },
    { id: 9, value: 'Gurgaon' },
    { id: 10, value: 'Noida' },
    { id: 11, value: 'Jaipur' },
    { id: 12, value: 'Surat' },
    { id: 13, value: 'Lucknow' },
    { id: 14, value: 'Bhubaneswar' },
];

export const jobTypes = [
    { id: 1, value: 'Remote' },
    { id: 2, value: 'Hybrid' },
    { id: 3, value: 'In-Office' },
];

export const minimumBasePay = [
    { id: 1, value: '0L' },
    { id: 2, value: '10L' },
    { id: 3, value: '20L' },
    { id: 4, value: '30L' },
    { id: 5, value: '40L' },
    { id: 6, value: '50L' },
    { id: 7, value: '60L' },
    { id: 8, value: '70L' },
]

export const techStack = [
    { id: 1, value: 'Angular' },
    { id: 2, value: 'React' },
    { id: 3, value: 'Vue' },
    { id: 4, value: 'Node' },
    { id: 5, value: 'Express' },
    { id: 6, value: 'MongoDB' },
    { id: 7, value: 'MySQL' },
    { id: 8, value: 'PostgreSQL' },
    { id: 9, value: 'Django' },
    { id: 10, value: 'Flask' },
    { id: 11, value: 'C++' },
    { id: 12, value: 'C' },
    { id: 13, value: 'C#' },
    { id: 14, value: 'Java' },
    { id: 15, value: 'Python' },
    { id: 16, value: 'PHP' },
    { id: 17, value: 'JavaScript' },
    { id: 18, value: 'TypeScript' },
    { id: 19, value: 'HTML' },
    { id: 20, value: 'CSS' },
    { id: 21, value: 'Bootstrap' },
]

export const companyNames = [
    "Weekday",
    "Accenture",
    "Cognizant",
    "Mindtree",
    "MPHASIS",
    "Deloitte",
    "Tata Consultancy Services (TCS)",
    "Infosys",
    "HCL Technologies",
    "Wipro",
    "Tech Mahindra",
    "Virtusa",
    "Amazon",
    "FlipKart"
];

export const companyLinks = [
    "https://assets-global.website-files.com/63359abeb97bf0d5ca346052/6336e2cc37e3c15b9c7c4487_Logo_new.png",
    "https://www.accenturealumni.com/login/wp-content/uploads/2021/03/cropped-favicon-512x.png",
    "https://logosandtypes.com/wp-content/uploads/2022/03/cognizant.svg",
    "https://seeklogo.com/images/M/mindtree-logo-021158128A-seeklogo.com.png",
    "https://companieslogo.com/img/orig/MPHASIS.NS-71626325.png?t=1612568622",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/DeloitteNewSmall.png/220px-DeloitteNewSmall.png",
    "https://ibsintelligence.com/wp-content/uploads/2021/09/TCS.jpg",
    "https://w7.pngwing.com/pngs/687/655/png-transparent-infosys-logo-thumbnail.png",
    "https://logos-world.net/wp-content/uploads/2022/07/HCL-Technologies-Logo.png",
    "https://i.pinimg.com/736x/16/f8/7a/16f87a2a909a06634e61d63d57e79bb0.jpg",
    "https://cdn-images.himalayas.app/5uzzzkokpkbovsy5tqbjbikg9h8i",
    "https://iconape.com/wp-content/files/ti/181166/png/181166.png",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Amazon_icon.svg/2500px-Amazon_icon.svg.png",
    "https://e7.pngegg.com/pngimages/946/191/png-clipart-flipkart-e-commerce-logo-bangalore-chief-executive-others-miscellaneous-blue-thumbnail.png"
];
// ⨯